### ISSUE TITLE
Coverage from 1990

### ISSUE THREAD

**Issue by AntoineAugusti** [Tutuchan/vacancesscolr#4]
Hello,

Just to let know you know that @DavidDoukhan submitted a PR https://github.com/AntoineAugusti/vacances-scolaires/pull/6 to add data since 1990! Cheers to him. You can update this package.

**Comment by Tutuchan** [comment]
Thanks, I'll check this out !

**Comment by Tutuchan** [comment]
I've finally taken the time to do it 😀
