### ISSUE TITLE
add 2019 and 2020 ?

### ISSUE THREAD

**Issue by GuillaumePressiat** [Tutuchan/vacancesscolr#5]
Hi,

Thanks for this package.
How to add 2019 and 2020 ?

Maybe I can do this.

Thanks,
G.

**Comment by Tutuchan** [comment]
Hey, thanks for reminding me to do this ! I updated the package with data from 1990 to 2021.

**Comment by GuillaumePressiat** [comment]
Just do it :) ! 

Thanks !
